name: pop_bubbles
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  audioplayers: ^0.19.1
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  get: ^4.3.8
  google_mobile_ads: ^0.13.3

dev_dependencies:
  flutter_flavorizr: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  lint: ^1.6.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/bubbles.png"

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "POP BUBBLES DEV"
      android:
        applicationId: "dev.popbubbles.www"
        firebase:
          config: "firebase/dev/google-services.json"
      ios:
        bundleId: "dev.popbubbles.www"
    prod:
      app:
        name: "POP BUBBLES"
      android:
        applicationId: "app.popbubbles.www"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "app.popbubbles.www"

flutter:
  uses-material-design: true
  assets:
    - assets/heart_fill.png
    - assets/heart_stroke.png
    - assets/the_end.gif
    - assets/pop.mp3
    - assets/danzon_da_pasion.mp3
    - assets/stomach_thumps.mp3
    - assets/bubble_bath.mp3

  fonts:
    - family: Odibee Sans Regular
      fonts:
        - asset: fonts/Odibee_Sans/OdibeeSans-Regular.ttf