name: pop_bubbles
description: A new Flutter project.
version: 1.0.2+3
publish_to: 'none'

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_flavorizr: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter_icons:
  #  image_path: "assets/bubbles.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  android: true # can specify file name here e.g. "ic_launcher"
  image_path_ios: "assets/bubbles.png"
  image_path_android: "assets/bubbles.png"
  adaptive_icon_background: "assets/bubbles.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/bubbles.png" # only available for Android 8.0 devices and above

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "POP BUBBLES DEV"
      android:
        applicationId: "dev.popbubbles.www"
        firebase:
          config: "firebase/dev/google-services.json"
      ios:
        bundleId: "dev.popbubbles.www"
    prod:
      app:
        name: "POP BUBBLES"
      android:
        applicationId: "app.popbubbles.www"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "app.popbubbles.www"

flutter:
  uses-material-design: true
  assets:
    - assets/heart_fill.webp
    - assets/heart_stroke.webp
    - assets/the_end.gif
    - assets/pop.aac
    - assets/cartoon.aac
    - assets/danzon_da_pasion.aac
    - assets/stomach_thumps.aac
    - assets/bubble_bath.aac

  fonts:
    - family: Odibee Sans Regular
      fonts:
        - asset: fonts/Odibee_Sans/OdibeeSans-Regular.ttf