name: pop_bubbles
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:

  uses-material-design: true